---
- name: Add Zabbix host
  hosts: zabbix_server
  vars:
    zabbix_host_ip: "185.174.168.10"
    zabbix_api_url: "http://185.174.168.26/zabbix/api_jsonrpc.php"
    zabbix_user: "admin"
    zabbix_password: "zabbix"
  tasks:
    - name: Create Zabbix host group
      zabbix_host_group:
        server_url: "{{ zabbix_api_url }}"
        login_user: "{{ zabbix_user }}"
        login_password: "{{ zabbix_password }}"
        name: "Patata"
        state: present

    - name: Add Zabbix host
      zabbix_host:
        server_url: "{{ zabbix_api_url }}"
        login_user: "{{ zabbix_user }}"
        login_password: "{{ zabbix_password }}"
        name: "Platano"
        interface_ip: "{{ zabbix_host_ip }}"
        interface_port: 10050
        groups:
          - "Patata"
        state: present
